package net.oktawia.insaneae2addons.defs;

import appeng.core.localization.LocalizationEnum;

public enum LangDefs implements LocalizationEnum {

    MOD_NAME("itemGroup.insaneae2addons", "Insane AE2 Addons"),

    ALWAYS("gui.insaneae2addons.always", "Always"),
    EQUALS("gui.insaneae2addons.equals", "Equals"),
    NOT_EQUALS("gui.insaneae2addons.not_equals", "Not Equals"),
    PLACE("gui.insaneae2addons.place", "Place"),
    BREAK("gui.insaneae2addons.break", "Break"),

    LEFT("gui.insaneae2addons.left", "Left"),
    RIGHT("gui.insaneae2addons.right", "Right"),
    UP("gui.insaneae2addons.up", "Up"),
    DOWN("gui.insaneae2addons.down", "Down"),
    FORWARDS("gui.insaneae2addons.forwards", "Forwards"),
    BACKWARDS("gui.insaneae2addons.backwards", "Backwards"),
    BACK("gui.insaneae2addons.back", "Back"),

    MOVE_FORWARD("gui.insaneae2addons.move_forward", "Move forward"),
    MOVE_BACKWARD("gui.insaneae2addons.move_backward", "Move backward"),
    MOVE_LEFT("gui.insaneae2addons.move_left", "Move left"),
    MOVE_RIGHT("gui.insaneae2addons.move_right", "Move right"),
    MOVE_UP("gui.insaneae2addons.move_up", "Move up"),
    MOVE_DOWN("gui.insaneae2addons.move_down", "Move down"),

    CONFIRM("gui.insaneae2addons.confirm", "Confirm"),
    GENERATE("gui.insaneae2addons.generate", "Generate"),
    FLIP_HORIZONTAL("gui.insaneae2addons.flip_horizontal", "Flip Horizontal"),
    FLIP_VERTICAL("gui.insaneae2addons.flip_vertical", "Flip Vertical"),
    ROTATE_CW("gui.insaneae2addons.rotate_cw", "Rotate CW"),
    VISUAL_ASSISTANCE("gui.insaneae2addons.visual_assistance", "Visual Assistance - fill region helper"),

    SHOW_PREVIEW("gui.insaneae2addons.show_preview", "Show Preview"),
    HIDE_PREVIEW("gui.insaneae2addons.hide_preview", "Hide Preview"),

    CORNER_SET_A("gui.insaneae2addons.corner_set_a", "Corner A set"),
    CORNER_SET_B("gui.insaneae2addons.corner_set_b", "Corner B set (origin)"),
    CORNER_RESET("gui.insaneae2addons.corner_reset", "Corners reset"),

    PROGRAM_SAVED("gui.insaneae2addons.program_saved", "Pattern saved!"),
    PROGRAM_INVALID("gui.insaneae2addons.program_invalid", "Pattern is invalid"),
    PROGRAM_NO_CODE("gui.insaneae2addons.program_no_code", "No program loaded"),
    SYNTAX_ERROR("gui.insaneae2addons.syntax_error", "Syntax Error!"),

    BUILDER_PATTERN_SUBSCREEN_TITLE("gui.insaneae2addons.builder_pattern_subscreen_title", "Fill Region"),
    ACTION("gui.insaneae2addons.action", "Action"),
    CHECK("gui.insaneae2addons.check", "Check"),
    CONDITION("gui.insaneae2addons.condition", "Condition"),
    PATTERN("gui.insaneae2addons.pattern", "Pattern"),
    OFFSET("gui.insaneae2addons.offset", "Offset"),
    WIDTH("gui.insaneae2addons.width", "Width"),
    HEIGHT("gui.insaneae2addons.height", "Height"),
    DEPTH("gui.insaneae2addons.depth", "Depth"),

    ENERGY_NEEDED("gui.insaneae2addons.energy_needed", "Energy needed: "),
    MISSING("gui.insaneae2addons.missing", "Missing:"),
    SKIP_MISSING_TOOLTIP("gui.insaneae2addons.skip_missing_tooltip", "Skip blocks that are missing from the network"),

    MIN("gui.insaneae2addons.min", "Min"),
    MAX("gui.insaneae2addons.max", "Max"),
    AMPERES("gui.insaneae2addons.amperes", "Amps"),
    FE_PER_TICK("gui.insaneae2addons.fe_per_tick", "FE/t"),
    AMPERE_METER_DIRECTION_LEFT_TO_RIGHT("gui.insaneae2addons.ampere_meter_direction_left_to_right", "Send power from left to right"),
    AMPERE_METER_DIRECTION_RIGHT_TO_LEFT("gui.insaneae2addons.ampere_meter_direction_right_to_left", "Send power from right to left"),
    AMPERE_METER_MIN_THRESHOLD("gui.insaneae2addons.ampere_meter_min_threshold", "Stop emitting redstone below this transfer rate"),
    AMPERE_METER_MAX_THRESHOLD("gui.insaneae2addons.ampere_meter_max_threshold", "Max out redstone above this transfer rate"),

    CONFIG_TITLE("gui.insaneae2addons.config.title", "Insane AE2 Addons"),
    CONFIG_CATEGORY_SETTINGS("gui.insaneae2addons.config.category.settings", "Settings"),
    CONFIG_SECTION_AUTOBUILDER("gui.insaneae2addons.config.section.autobuilder", "Autobuilder"),
    CONFIG_SECTION_AUTOBUILDER_DESC("gui.insaneae2addons.config.section.autobuilder.desc", "Places or breaks blocks in a region based on a builder pattern."),
    CONFIG_ENTRY_COST_MULTIPLIER("gui.insaneae2addons.config.entry.cost_multiplier", "Cost multiplier"),
    CONFIG_DESC_COST_MULTIPLIER("gui.insaneae2addons.config.desc.cost_multiplier", "FE cost multiplier for the autobuilder."),
    CONFIG_ENTRY_MINE_DELAY("gui.insaneae2addons.config.entry.mine_delay", "Mine delay"),
    CONFIG_DESC_MINE_DELAY("gui.insaneae2addons.config.desc.mine_delay", "Ticks to wait after each broken block."),
    CONFIG_ENTRY_SPEED("gui.insaneae2addons.config.entry.speed", "Speed"),
    CONFIG_DESC_SPEED("gui.insaneae2addons.config.desc.speed", "Operations per tick the autobuilder can perform."),
    CONFIG_ENTRY_PREVIEW_LIMIT("gui.insaneae2addons.config.entry.preview_limit", "Preview limit"),
    CONFIG_DESC_PREVIEW_LIMIT("gui.insaneae2addons.config.desc.preview_limit", "How many preview blocks the autobuilder can show at once."),

    CONFIG_SECTION_RESEARCH("gui.insaneae2addons.config.section.research", "Research"),
    CONFIG_SECTION_RESEARCH_DESC("gui.insaneae2addons.config.section.research.desc", "The research multiblock unlocks insane fabrication recipes onto a Data Drive."),
    CONFIG_ENTRY_RESEARCH_REQUIRED("gui.insaneae2addons.config.entry.research_required", "Research required"),
    CONFIG_DESC_RESEARCH_REQUIRED("gui.insaneae2addons.config.desc.research_required", "When on, insane fabrication recipes require the matching research unlock on a Data Drive."),
    CONFIG_ENTRY_RESEARCH_UNIT_EXTRA_Q_BLOCKS("gui.insaneae2addons.config.entry.research_unit_extra_q_blocks", "Extra core blocks"),
    CONFIG_DESC_RESEARCH_UNIT_EXTRA_Q_BLOCKS("gui.insaneae2addons.config.desc.research_unit_extra_q_blocks", "Extra blocks allowed in the 3x3 core of the Research Unit and how much computation each grants per block. One entry per line as namespace:block=computation, e.g. minecraft:diamond_block=8. Built-in crafting storage blocks (1k-256k) are always allowed and counted separately. Leave empty for defaults only."),
    CONFIG_ENTRY_RESEARCH_UNIT_COMPUTATION_DIVISOR("gui.insaneae2addons.config.entry.research_unit_computation_divisor", "Computation divisor"),
    CONFIG_DESC_RESEARCH_UNIT_COMPUTATION_DIVISOR("gui.insaneae2addons.config.desc.research_unit_computation_divisor", "Summed tier value of the core blocks is divided by this to get base computation. Lower means more computation per core."),
    CONFIG_ENTRY_RESEARCH_UNIT_COMPUTATION_POWER_COST("gui.insaneae2addons.config.entry.research_unit_computation_power_cost", "Power per computation"),
    CONFIG_DESC_RESEARCH_UNIT_COMPUTATION_POWER_COST("gui.insaneae2addons.config.desc.research_unit_computation_power_cost", "AE drawn per point of computation per tick while researching."),
    CONFIG_ENTRY_RESEARCH_UNIT_FLUID_DIVISOR("gui.insaneae2addons.config.entry.research_unit_fluid_divisor", "Fluid divisor"),
    CONFIG_DESC_RESEARCH_UNIT_FLUID_DIVISOR("gui.insaneae2addons.config.desc.research_unit_fluid_divisor", "Computation divided by this gives research fluid (mB) consumed per tick."),
    CONFIG_ENTRY_RESEARCH_UNIT_FLUID_BUFFER("gui.insaneae2addons.config.entry.research_unit_fluid_buffer", "Fluid buffer"),
    CONFIG_DESC_RESEARCH_UNIT_FLUID_BUFFER("gui.insaneae2addons.config.desc.research_unit_fluid_buffer", "Research fluid buffer capacity (mB) held by the research unit."),
    CONFIG_ENTRY_RESEARCH_UNIT_POWER_BUFFER("gui.insaneae2addons.config.entry.research_unit_power_buffer", "Power buffer"),
    CONFIG_DESC_RESEARCH_UNIT_POWER_BUFFER("gui.insaneae2addons.config.desc.research_unit_power_buffer", "AE power buffer capacity held by the research unit."),
    CONFIG_ENTRY_RESEARCH_STATION_PEDESTAL_RANGE("gui.insaneae2addons.config.entry.research_station_pedestal_range", "Pedestal range"),
    CONFIG_DESC_RESEARCH_STATION_PEDESTAL_RANGE("gui.insaneae2addons.config.desc.research_station_pedestal_range", "Radius in blocks around the research station scanned for pedestals."),

    CONFIG_SECTION_ENTITY_TICKER("gui.insaneae2addons.config.section.entity_ticker", "Entity ticker"),
    CONFIG_SECTION_ENTITY_TICKER_DESC("gui.insaneae2addons.config.section.entity_ticker.desc", "A cable part that force-ticks the block entity it faces, multiplying its speed with speed cards."),
    CONFIG_ENTRY_ENTITY_TICKER_ENABLED("gui.insaneae2addons.config.entry.entity_ticker_enabled", "Enabled"),
    CONFIG_DESC_ENTITY_TICKER_ENABLED("gui.insaneae2addons.config.desc.entity_ticker_enabled", "Enables the entity ticker part."),
    CONFIG_ENTRY_ENTITY_TICKER_COST("gui.insaneae2addons.config.entry.entity_ticker_cost", "Cost"),
    CONFIG_DESC_ENTITY_TICKER_COST("gui.insaneae2addons.config.desc.entity_ticker_cost", "Base AE cost per tick. Scales by 4^(speed cards)."),
    CONFIG_ENTRY_ENTITY_TICKER_MAX_SPEED_CARDS("gui.insaneae2addons.config.entry.entity_ticker_max_speed_cards", "Max speed cards"),
    CONFIG_DESC_ENTITY_TICKER_MAX_SPEED_CARDS("gui.insaneae2addons.config.desc.entity_ticker_max_speed_cards", "Maximum speed cards the entity ticker accepts. Changing this takes effect after a restart."),
    CONFIG_ENTRY_ENTITY_TICKER_BLACKLIST("gui.insaneae2addons.config.entry.entity_ticker_blacklist", "Blacklist"),
    CONFIG_DESC_ENTITY_TICKER_BLACKLIST("gui.insaneae2addons.config.desc.entity_ticker_blacklist", "Block ids the entity ticker refuses to tick. One entry per line, e.g. minecraft:spawner."),

    ENTITY_TICKER_ENERGY("gui.insaneae2addons.entity_ticker_energy", "Energy Usage: %s AE/t"),
    ENTITY_TICKER_SPEED("gui.insaneae2addons.entity_ticker_speed", "Current multiplier: %d"),
    ENTITY_TICKER_INFO_1("gui.insaneae2addons.entity_ticker_info_1", "Each card multiplies"),
    ENTITY_TICKER_INFO_2("gui.insaneae2addons.entity_ticker_info_2", "machine speed by 2"),

    CONFIG_SECTION_NBT_TOOLS("gui.insaneae2addons.config.section.nbt_tools", "NBT tools"),
    CONFIG_SECTION_NBT_TOOLS_DESC("gui.insaneae2addons.config.section.nbt_tools.desc", "NBT view cell and NBT filtering buses match items by their NBT via a matcher expression."),
    CONFIG_ENTRY_NBT_VIEW_CELL("gui.insaneae2addons.config.entry.nbt_view_cell", "NBT view cell"),
    CONFIG_DESC_NBT_VIEW_CELL("gui.insaneae2addons.config.desc.nbt_view_cell", "Enables the NBT view cell and its recognition in AE2 view cell slots."),
    CONFIG_ENTRY_NBT_STORAGE_BUS("gui.insaneae2addons.config.entry.nbt_storage_bus", "NBT storage bus"),
    CONFIG_DESC_NBT_STORAGE_BUS("gui.insaneae2addons.config.desc.nbt_storage_bus", "Enables the NBT storage bus."),
    CONFIG_ENTRY_NBT_EXPORT_BUS("gui.insaneae2addons.config.entry.nbt_export_bus", "NBT export bus"),
    CONFIG_DESC_NBT_EXPORT_BUS("gui.insaneae2addons.config.desc.nbt_export_bus", "Enables the NBT export bus."),
    CONFIG_ENTRY_NBT_EXPORT_BUS_TRANSFER_FACTOR("gui.insaneae2addons.config.entry.nbt_export_bus_transfer_factor", "Export transfer factor"),
    CONFIG_DESC_NBT_EXPORT_BUS_TRANSFER_FACTOR("gui.insaneae2addons.config.desc.nbt_export_bus_transfer_factor", "Items moved per operation by the NBT export bus (operations times this factor)."),

    CONFIG_SECTION_AMPERE_METER("gui.insaneae2addons.config.section.ampere_meter", "Ampere meter"),
    CONFIG_SECTION_AMPERE_METER_DESC("gui.insaneae2addons.config.section.ampere_meter.desc", "An inline block that measures FE/EU throughput and can emit redstone based on the transfer rate."),
    CONFIG_ENTRY_AMPERE_METER_INACTIVITY_RESET("gui.insaneae2addons.config.entry.ampere_meter_inactivity_reset", "Inactivity reset ticks"),
    CONFIG_DESC_AMPERE_METER_INACTIVITY_RESET("gui.insaneae2addons.config.desc.ampere_meter_inactivity_reset", "Ticks without any transfer after which the displayed rate resets to zero."),

    CONFIG_SECTION_BROKEN_PATTERN_PROVIDER("gui.insaneae2addons.config.section.broken_pattern_provider", "Broken pattern provider"),
    CONFIG_SECTION_BROKEN_PATTERN_PROVIDER_DESC("gui.insaneae2addons.config.section.broken_pattern_provider.desc", "A pattern provider with a single pattern slot."),
    CONFIG_ENTRY_BROKEN_PATTERN_PROVIDER_ENABLED("gui.insaneae2addons.config.entry.broken_pattern_provider_enabled", "Enabled"),
    CONFIG_DESC_BROKEN_PATTERN_PROVIDER_ENABLED("gui.insaneae2addons.config.desc.broken_pattern_provider_enabled", "Hides the broken pattern provider from JEI/EMI and marks it in the tooltip when off. Placed ones keep working."),

    CONFIG_SECTION_PROVIDER_CARDS("gui.insaneae2addons.config.section.provider_cards", "Provider cards"),
    CONFIG_SECTION_PROVIDER_CARDS_DESC("gui.insaneae2addons.config.section.provider_cards.desc", "Player/automation upgrade cards for the crazy pattern provider, restricting which requests it serves."),
    CONFIG_ENTRY_PROVIDER_CARDS_ENABLED("gui.insaneae2addons.config.entry.provider_cards_enabled", "Enabled"),
    CONFIG_DESC_PROVIDER_CARDS_ENABLED("gui.insaneae2addons.config.desc.provider_cards_enabled", "Hides the player/automation cards from JEI/EMI, marks them in the tooltip, and disables their source filtering when off."),

    CONFIG_SECTION_AUTO_ENCHANTER("gui.insaneae2addons.config.section.auto_enchanter", "Auto enchanter"),
    CONFIG_SECTION_AUTO_ENCHANTER_DESC("gui.insaneae2addons.config.section.auto_enchanter.desc", "A machine under an enchanting table that enchants items from the network using lapis and stored XP."),
    CONFIG_ENTRY_AUTO_ENCHANTER_ENABLED("gui.insaneae2addons.config.entry.auto_enchanter_enabled", "Enabled"),
    CONFIG_DESC_AUTO_ENCHANTER_ENABLED("gui.insaneae2addons.config.desc.auto_enchanter_enabled", "Hides the auto enchanter from JEI/EMI, marks it in the tooltip, and stops it working when off."),
    CONFIG_ENTRY_AUTO_ENCHANTER_COST("gui.insaneae2addons.config.entry.auto_enchanter_cost", "Cost"),
    CONFIG_DESC_AUTO_ENCHANTER_COST("gui.insaneae2addons.config.desc.auto_enchanter_cost", "XP cost multiplier for the auto enchanter."),

    AUTO_ENCHANTER_INPUT("gui.insaneae2addons.auto_enchanter_input", "Input"),
    AUTO_ENCHANTER_OUTPUT("gui.insaneae2addons.auto_enchanter_output", "Output"),
    AUTO_ENCHANTER_XP("gui.insaneae2addons.auto_enchanter_xp", "Stored XP"),
    AUTO_ENCHANTER_LBL_CHEAP("gui.insaneae2addons.auto_enchanter_lbl_cheap", "Cheap"),
    AUTO_ENCHANTER_LBL_MEDIUM("gui.insaneae2addons.auto_enchanter_lbl_medium", "Medium"),
    AUTO_ENCHANTER_LBL_EXP("gui.insaneae2addons.auto_enchanter_lbl_exp", "Exp"),
    ENCHANTER_CHEAP("gui.insaneae2addons.enchanter_cheap", "Cheap enchant (top slot)"),
    ENCHANTER_MEDIUM("gui.insaneae2addons.enchanter_medium", "Medium enchant (middle slot)"),
    ENCHANTER_EXP("gui.insaneae2addons.enchanter_exp", "Expensive enchant (bottom slot)"),
    ENCHANTER_LAPIS_ON("gui.insaneae2addons.enchanter_lapis_on", "Auto-supply lapis: on"),
    ENCHANTER_LAPIS_OFF("gui.insaneae2addons.enchanter_lapis_off", "Auto-supply lapis: off"),
    ENCHANTER_BOOK_ON("gui.insaneae2addons.enchanter_book_on", "Auto-supply books: on"),
    ENCHANTER_BOOK_OFF("gui.insaneae2addons.enchanter_book_off", "Auto-supply books: off"),
    ENCHANTER_REQUIRED("gui.insaneae2addons.enchanter_required", "~Required: %s"),

    CONFIG_SECTION_ENERGY_STORAGE("gui.insaneae2addons.config.section.energy_storage", "Energy storage"),
    CONFIG_SECTION_ENERGY_STORAGE_DESC("gui.insaneae2addons.config.section.energy_storage.desc", "Standalone AE energy cells in ten tiers that store network power, crafted in the entropy cradle."),
    CONFIG_ENTRY_ENERGY_STORAGE_ENABLED("gui.insaneae2addons.config.entry.energy_storage_enabled", "Enabled"),
    CONFIG_DESC_ENERGY_STORAGE_ENABLED("gui.insaneae2addons.config.desc.energy_storage_enabled", "Hides the energy storage blocks from JEI/EMI and marks them in the tooltip when off. Placed ones keep working."),
    CONFIG_ENTRY_ENERGY_STORAGE_CAPACITY_MULTIPLIER("gui.insaneae2addons.config.entry.energy_storage_capacity_multiplier", "Capacity multiplier"),
    CONFIG_DESC_ENERGY_STORAGE_CAPACITY_MULTIPLIER("gui.insaneae2addons.config.desc.energy_storage_capacity_multiplier", "Multiplies the stored-energy capacity of every energy storage tier."),

    CONFIG_SECTION_ENTROPY_CRADLE("gui.insaneae2addons.config.section.entropy_cradle", "Entropy cradle"),
    CONFIG_SECTION_ENTROPY_CRADLE_DESC("gui.insaneae2addons.config.section.entropy_cradle.desc", "A multiblock that stores AE power as FE and transmutes a block pattern in its chamber on a redstone pulse."),
    CONFIG_ENTRY_CRADLE_CAPACITY("gui.insaneae2addons.config.entry.cradle_capacity", "Capacity"),
    CONFIG_DESC_CRADLE_CAPACITY("gui.insaneae2addons.config.desc.cradle_capacity", "Maximum FE the entropy cradle can store."),
    CONFIG_ENTRY_CRADLE_CHARGING_SPEED("gui.insaneae2addons.config.entry.cradle_charging_speed", "Charging speed"),
    CONFIG_DESC_CRADLE_CHARGING_SPEED("gui.insaneae2addons.config.desc.cradle_charging_speed", "Maximum AE the entropy cradle can pull from the network per tick."),
    CONFIG_ENTRY_CRADLE_COST("gui.insaneae2addons.config.entry.cradle_cost", "Cost"),
    CONFIG_DESC_CRADLE_COST("gui.insaneae2addons.config.desc.cradle_cost", "FE consumed by the entropy cradle per transmutation pulse."),

    NBT_VIEW_CELL_CONFIRM("gui.insaneae2addons.nbt_view_cell_confirm", "Save filter"),
    NBT_VIEW_CELL_INPUT("gui.insaneae2addons.nbt_view_cell_input", "NBT matcher expression"),
    NBT_EXPORT_CONFIRM("gui.insaneae2addons.nbt_export_confirm", "Save filter"),
    NBT_EXPORT_LOAD("gui.insaneae2addons.nbt_export_load", "Load NBT from the item in the slot"),
    NBT_STORAGE_CONFIRM("gui.insaneae2addons.nbt_storage_confirm", "Save filter"),
    NBT_STORAGE_LOAD("gui.insaneae2addons.nbt_storage_load", "Load NBT from the item in the slot"),
    NBT_FILTER_SAVED("gui.insaneae2addons.nbt_filter_saved", "Filter saved"),
    NBT_SYNTAX_ERROR("gui.insaneae2addons.nbt_syntax_error", "Syntax error:"),
    NBT_EXPORT_FORMAT("gui.insaneae2addons.nbt_export_format", "Format the expression"),
    NBT_STORAGE_FORMAT("gui.insaneae2addons.nbt_storage_format", "Format the expression"),

    CRADLE_DESC_EC_1K("ec.1k", "1k Energy Cell can hold over 8M AE (16M FE)"),
    CRADLE_DESC_EC_4K("ec.4k", "4k Energy Cell can hold over 32M AE (64M FE)"),
    CRADLE_DESC_EC_16K("ec.16k", "16k Energy Cell can hold over 128M AE (256M FE)"),
    CRADLE_DESC_EC_64K("ec.64k", "64k Energy Cell can hold over 512M AE (1G FE)"),
    CRADLE_DESC_EC_256K("ec.256k", "256k Energy Cell can hold over 2G AE (4G FE)"),
    CRADLE_DESC_EC_DENSE_1K("ec.dense.1k", "1k Dense Energy Cell can hold over 8G AE (16G FE)"),
    CRADLE_DESC_EC_DENSE_4K("ec.dense.4k", "4k Dense Energy Cell can hold over 32G AE (64G FE)"),
    CRADLE_DESC_EC_DENSE_16K("ec.dense.16k", "16k Dense Energy Cell can hold over 128G AE (256G FE)"),
    CRADLE_DESC_EC_DENSE_64K("ec.dense.64k", "64k Dense Energy Cell can hold over 512G AE (1T FE)"),
    CRADLE_DESC_EC_DENSE_256K("ec.dense.256k", "256k Dense Energy Cell can hold over 2T AE (4T FE)"),

    RESEARCH_RECIPE_PROGRESS("gui.insaneae2addons.research_recipe_progress", "Research progress"),
    RESEARCH_STORED_FLUID("gui.insaneae2addons.research_stored_fluid", "Stored research fluid"),
    RESEARCH_STORED_POWER("gui.insaneae2addons.research_stored_power", "Stored power"),
    RESEARCH_LOADING("gui.insaneae2addons.research_loading", "Researching..."),
    RESEARCH_DEV_UNLOCK("gui.insaneae2addons.research_dev_unlock", "Unlock all researches to the drive"),
    RESEARCH_UNIT_COMPUTATION("gui.insaneae2addons.research_unit_computation", "Computation: "),
    RESEARCH_UNIT_COOLANT("gui.insaneae2addons.research_unit_coolant", "Fluid use: "),
    RESEARCH_UNIT_POWER("gui.insaneae2addons.research_unit_power", "Power use: "),
    RESEARCH_UNIT_BUFFER("gui.insaneae2addons.research_unit_buffer", "Power buffer: "),
    RESEARCH_PEDESTAL_COMPUTATION("gui.insaneae2addons.research_pedestal_computation", "Computation: "),
    RESEARCH_PEDESTAL_INVALID("gui.insaneae2addons.research_pedestal_invalid", "No unit connected"),
    RESEARCH_PEDESTAL_MULTIPLE_UNITS("gui.insaneae2addons.research_pedestal_multiple_units", "Multiple units connected"),
    RESEARCH_PEDESTAL_UNIT_SHARED("gui.insaneae2addons.research_pedestal_unit_shared", "Unit shared with another pedestal"),
    DATA_DRIVE_RESEARCHES("gui.insaneae2addons.data_drive_researches", "Researches"),
    RECIPE_FABRICATOR_RESEARCH_DISK("gui.insaneae2addons.recipe_fabricator_research_disk", "Data Drive"),

    RESEARCH_CATEGORY("emi.insaneae2addons.category_research", "Research Station"),
    CRADLE_CATEGORY("emi.insaneae2addons.category_cradle", "Entropy Cradle"),
    CRADLE_INPUTS("gui.insaneae2addons.cradle_inputs", "Inputs"),
    CRADLE_OUTPUT("gui.insaneae2addons.cradle_output", "Output"),
    CRADLE_LAYER_PREFIX("gui.insaneae2addons.cradle_layer_prefix", "Y"),
    CRADLE_LAYER_ALL("gui.insaneae2addons.cradle_layer_all", "All"),
    CRADLE_LAYER_TOOLTIP("gui.insaneae2addons.cradle_layer_tooltip", "Cycle through the chamber layers"),
    CRADLE_TOGGLE_LABEL("gui.insaneae2addons.cradle_toggle_label", "C"),
    CRADLE_ON("gui.insaneae2addons.cradle_on", "On"),
    CRADLE_OFF("gui.insaneae2addons.cradle_off", "Off"),
    CRADLE_TOGGLE_TOOLTIP("gui.insaneae2addons.cradle_toggle_tooltip", "Toggle the surrounding cradle structure"),
    RESEARCH_PEDESTAL_COMPACT("gui.insaneae2addons.research_pedestal_compact", "%s c"),
    RESEARCH_OUTPUT_LABEL("gui.insaneae2addons.research_output_label", "Unlocks"),
    RESEARCH_OUTPUT_DISK_NOTE("gui.insaneae2addons.research_output_disk_note", "written to Data Drive"),
    RESEARCH_DRIVE_TOOLTIP_1("gui.insaneae2addons.research_drive_tooltip_1", "Completing this research writes its key to a Data Drive."),
    RESEARCH_DRIVE_TOOLTIP_2("gui.insaneae2addons.research_drive_tooltip_2", "Insert that drive into the Recipe Fabricator to unlock gated recipes."),
    RESEARCH_DURATION("gui.insaneae2addons.research_duration", "Min. time: %s s"),
    RESEARCH_UNLOCKS("gui.insaneae2addons.research_unlocks", "Unlocks: %s"),
    RESEARCH_GATE_REQUIRES("gui.insaneae2addons.research_gate_requires", "Requires research: %s"),
    RESEARCH_GATE_HINT("gui.insaneae2addons.research_gate_hint", "Complete the research and insert its Data Drive into the Recipe Fabricator."),

    RESEARCH_STATUS_IDLE("gui.insaneae2addons.research_status.idle", "Idle"),
    RESEARCH_STATUS_READY("gui.insaneae2addons.research_status.ready", "Ready"),
    RESEARCH_STATUS_WORKING("gui.insaneae2addons.research_status.working", "Working"),
    RESEARCH_STATUS_NO_DATA_DRIVE("gui.insaneae2addons.research_status.no_data_drive", "No Data Drive"),
    RESEARCH_STATUS_NO_MATCHING_RECIPE("gui.insaneae2addons.research_status.no_matching_recipe", "No matching research"),
    RESEARCH_STATUS_MISSING_ITEMS("gui.insaneae2addons.research_status.missing_items", "Missing items"),
    RESEARCH_STATUS_NOT_ENOUGH_POWER("gui.insaneae2addons.research_status.not_enough_power", "Not enough power"),
    RESEARCH_STATUS_OUT_OF_RESEARCH_FLUID("gui.insaneae2addons.research_status.out_of_research_fluid", "Out of research fluid"),
    RESEARCH_STATUS_FLUID_LOW("gui.insaneae2addons.research_status.fluid_low", "Research fluid low"),
    RESEARCH_STATUS_NOT_ENOUGH_COMPUTATION("gui.insaneae2addons.research_status.not_enough_computation", "Not enough computation"),
    RESEARCH_STATUS_STRUCTURE_INCOMPLETE("gui.insaneae2addons.research_status.structure_incomplete", "Structure incomplete"),
    RESEARCH_STATUS_ALREADY_UNLOCKED("gui.insaneae2addons.research_status.already_unlocked", "Already unlocked");

    private final String key;
    private final String value;

    LangDefs(String key, String value) {
        this.key = key;
        this.value = value;
    }

    @Override
    public String getTranslationKey() {
        return key;
    }

    @Override
    public String getEnglishText() {
        return value;
    }
}
