pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
    plugins {
        id 'com.diffplug.spotless' version '6.25.0'
    }
}

rootProject.name = 'crazyae2addons'
include 'insane'