package net.oktawia.crazyae2addons.defs;

import appeng.core.localization.LocalizationEnum;

public enum LangDefs implements LocalizationEnum {

    CONFIG_TITLE("screen.crazyae2addons.config.title", "Crazy AE2 Addons"),
    CONFIG_CATEGORY_SETTINGS("screen.crazyae2addons.config.category.settings", "Settings"),
    CONFIG_SECTION_DISPLAY("screen.crazyae2addons.config.section.display", "Display"),
    CONFIG_SECTION_EMITTER_TERMINAL("screen.crazyae2addons.config.section.emitter_terminal", "Emitter Terminal"),
    CONFIG_SECTION_WIRELESS_NOTIFICATION_TERMINAL("screen.crazyae2addons.config.section.wireless_notification_terminal", "Wireless Notification Terminal"),
    CONFIG_SECTION_MULTI_LEVEL_EMITTER("screen.crazyae2addons.config.section.multi_level_emitter", "Multi Level Emitter"),
    CONFIG_SECTION_TAG_LEVEL_EMITTER("screen.crazyae2addons.config.section.tag_level_emitter", "Tag Level Emitter"),
    CONFIG_SECTION_REDSTONE_EMITTER_TERMINAL("screen.crazyae2addons.config.section.redstone_emitter_terminal", "Redstone Emitter / Terminal"),
    CONFIG_SECTION_WORMHOLE("screen.crazyae2addons.config.section.wormhole", "Wormhole"),
    CONFIG_SECTION_ROUND_ROBIN_P2P("screen.crazyae2addons.config.section.round_robin_p2p", "Round Robin P2P"),
    CONFIG_SECTION_CPU_PRIORITIES("screen.crazyae2addons.config.section.cpu_priorities", "CPU Priorities"),
    CONFIG_SECTION_TAG_VIEW_CELL("screen.crazyae2addons.config.section.tag_view_cell", "Tag View Cell"),
    CONFIG_SECTION_PATTERN_MULTIPLIER("screen.crazyae2addons.config.section.pattern_multiplier", "Pattern Multiplier"),
    CONFIG_SECTION_CRAZY_PATTERN_PROVIDER("screen.crazyae2addons.config.section.crazy_pattern_provider", "Crazy Pattern Provider"),
    CONFIG_SECTION_EJECTOR("screen.crazyae2addons.config.section.ejector", "Ejector"),
    CONFIG_ENTRY_ENABLED("screen.crazyae2addons.config.entry.enabled", "Enabled"),
    CONFIG_ENTRY_IMAGES_ENABLED("screen.crazyae2addons.config.entry.images_enabled", "Images Enabled"),
    CONFIG_ENTRY_STOCK_ENABLED("screen.crazyae2addons.config.entry.stock_enabled", "Stock Enabled"),
    CONFIG_ENTRY_ICONS_ENABLED("screen.crazyae2addons.config.entry.icons_enabled", "Icons Enabled"),
    CONFIG_ENTRY_DELTA_ENABLED("screen.crazyae2addons.config.entry.delta_enabled", "Delta Enabled"),
    CONFIG_ENTRY_WIRELESS_ENABLED("screen.crazyae2addons.config.entry.wireless_enabled", "Wireless Enabled"),
    CONFIG_ENTRY_CONFIG_SLOTS("screen.crazyae2addons.config.entry.config_slots", "Config Slots"),
    CONFIG_ENTRY_TELEPORTATION_ENABLED("screen.crazyae2addons.config.entry.teleportation_enabled", "Teleportation Enabled"),
    CONFIG_ENTRY_NESTED_P2PS_ENABLED("screen.crazyae2addons.config.entry.nested_p2ps_enabled", "Nested P2Ps Enabled"),
    CONFIG_ENTRY_ITEM_PROXY_ENABLED("screen.crazyae2addons.config.entry.item_proxy_enabled", "Item Proxy Enabled"),
    CONFIG_ENTRY_FLUID_PROXY_ENABLED("screen.crazyae2addons.config.entry.fluid_proxy_enabled", "Fluid Proxy Enabled"),
    CONFIG_ENTRY_FE_PROXY_ENABLED("screen.crazyae2addons.config.entry.fe_proxy_enabled", "FE Proxy Enabled"),
    CONFIG_ENTRY_EU_PROXY_ENABLED("screen.crazyae2addons.config.entry.eu_proxy_enabled", "EU Proxy Enabled"),
    CONFIG_ENTRY_OTHER_CAPABILITY_PROXY_ENABLED("screen.crazyae2addons.config.entry.other_capability_proxy_enabled", "Other Capability Proxy Enabled"),
    CONFIG_ENTRY_MERGED_CAPABILITY_PROXY_ENABLED("screen.crazyae2addons.config.entry.merged_capability_proxy_enabled", "Merged Capability Proxy Enabled"),
    CONFIG_ENTRY_REMOTE_INTERACTIONS_ENABLED("screen.crazyae2addons.config.entry.remote_interactions_enabled", "Remote Interactions Enabled"),
    CONFIG_ENTRY_ITEM_P2P_ENABLED("screen.crazyae2addons.config.entry.item_p2p_enabled", "Item P2P Enabled"),
    CONFIG_ENTRY_FLUID_P2P_ENABLED("screen.crazyae2addons.config.entry.fluid_p2p_enabled", "Fluid P2P Enabled"),
    CONFIG_ENTRY_BLOCK_ENABLED("screen.crazyae2addons.config.entry.block_enabled", "Block Enabled"),
    CONFIG_ENTRY_PART_ENABLED("screen.crazyae2addons.config.entry.part_enabled", "Part Enabled"),
    CONFIG_ENTRY_MAX_UPGRADES_UNLIMITED("screen.crazyae2addons.config.entry.max_upgrades_unlimited", "Max Upgrades (-1 = unlimited)"),
    CONFIG_ENTRY_CRAFT_MISSING_ENABLED("screen.crazyae2addons.config.entry.craft_missing_enabled", "Craft Missing Enabled"),
    CONFIG_ENTRY_COST_PER_BLOCK("screen.crazyae2addons.config.entry.cost_per_block", "Cost per Block"),
    CONFIG_ENTRY_BASE_INTERNAL_POWER_CAPACITY("screen.crazyae2addons.config.entry.base_internal_power_capacity", "Base Internal Power Capacity"),
    CONFIG_ENTRY_MAX_STRUCTURE_SIZE_UNLIMITED("screen.crazyae2addons.config.entry.max_structure_size_unlimited", "Max Structure Size (-1 = unlimited)"),
    CONFIG_SECTION_DISPLAY_DESC_1("screen.crazyae2addons.config.section.display.desc.1", "Display feature."),
    CONFIG_SECTION_DISPLAY_DESC_2("screen.crazyae2addons.config.section.display.desc.2", "A part that renders dynamic text, images, and AE2-related data."),
    CONFIG_SECTION_DISPLAY_DESC_3("screen.crazyae2addons.config.section.display.desc.3", "Supports token-based content, colors, icons, stock/delta rendering, and merged multi-display surfaces."),
    CONFIG_SECTION_EMITTER_TERMINAL_DESC_1("screen.crazyae2addons.config.section.emitter_terminal.desc.1", "The emitter terminal allows the player to access, query, and configure"),
    CONFIG_SECTION_EMITTER_TERMINAL_DESC_2("screen.crazyae2addons.config.section.emitter_terminal.desc.2", "all level emitters in the connected grid from a single terminal."),
    CONFIG_SECTION_WIRELESS_NOTIFICATION_TERMINAL_DESC_1("screen.crazyae2addons.config.section.wireless_notification_terminal.desc.1", "The wireless notification terminal allows the player to configure"),
    CONFIG_SECTION_WIRELESS_NOTIFICATION_TERMINAL_DESC_2("screen.crazyae2addons.config.section.wireless_notification_terminal.desc.2", "tracked resources in the connected grid and display their amounts"),
    CONFIG_SECTION_WIRELESS_NOTIFICATION_TERMINAL_DESC_3("screen.crazyae2addons.config.section.wireless_notification_terminal.desc.3", "when they are above or below a given threshold."),
    CONFIG_SECTION_MULTI_LEVEL_EMITTER_DESC_1("screen.crazyae2addons.config.section.multi_level_emitter.desc.1", "The multi level emitter tracks and triggers"),
    CONFIG_SECTION_MULTI_LEVEL_EMITTER_DESC_2("screen.crazyae2addons.config.section.multi_level_emitter.desc.2", "multiple conditions at once."),
    CONFIG_SECTION_TAG_LEVEL_EMITTER_DESC_1("screen.crazyae2addons.config.section.tag_level_emitter.desc.1", "The tag level emitter tracks resources based on a tag expression"),
    CONFIG_SECTION_TAG_LEVEL_EMITTER_DESC_2("screen.crazyae2addons.config.section.tag_level_emitter.desc.2", "and can monitor multiple resources at once."),
    CONFIG_SECTION_REDSTONE_EMITTER_TERMINAL_DESC_1("screen.crazyae2addons.config.section.redstone_emitter_terminal.desc.1", "The redstone terminal allows the player to control the redstone output"),
    CONFIG_SECTION_REDSTONE_EMITTER_TERMINAL_DESC_2("screen.crazyae2addons.config.section.redstone_emitter_terminal.desc.2", "of connected redstone emitters."),
    CONFIG_SECTION_WORMHOLE_DESC_1("screen.crazyae2addons.config.section.wormhole.desc.1", "Wormhole acts as a universal capability proxy and allows remote interactions or teleportation."),
    CONFIG_SECTION_WORMHOLE_DESC_2("screen.crazyae2addons.config.section.wormhole.desc.2", "The tunnel always forwards from any output to the input,"),
    CONFIG_SECTION_WORMHOLE_DESC_3("screen.crazyae2addons.config.section.wormhole.desc.3", "or from the input to the closest output."),
    CONFIG_SECTION_WORMHOLE_DESC_4("screen.crazyae2addons.config.section.wormhole.desc.4", "It never splits resources between multiple outputs."),
    CONFIG_SECTION_WORMHOLE_DESC_5("screen.crazyae2addons.config.section.wormhole.desc.5", "It can merge from many outputs to the same input."),
    CONFIG_SECTION_ROUND_ROBIN_P2P_DESC_1("screen.crazyae2addons.config.section.round_robin_p2p.desc.1", "Round robin P2P tunnels always split inputs evenly between all outputs,"),
    CONFIG_SECTION_ROUND_ROBIN_P2P_DESC_2("screen.crazyae2addons.config.section.round_robin_p2p.desc.2", "even across multiple insertions."),
    CONFIG_SECTION_CPU_PRIORITIES_DESC_1("screen.crazyae2addons.config.section.cpu_priorities.desc.1", "CPU priorities make higher-priority CPUs receive crafting jobs more often,"),
    CONFIG_SECTION_CPU_PRIORITIES_DESC_2("screen.crazyae2addons.config.section.cpu_priorities.desc.2", "receive crafted results before lower-priority CPUs,"),
    CONFIG_SECTION_CPU_PRIORITIES_DESC_3("screen.crazyae2addons.config.section.cpu_priorities.desc.3", "and use machines before lower-priority CPUs."),
    CONFIG_SECTION_TAG_VIEW_CELL_DESC_1("screen.crazyae2addons.config.section.tag_view_cell.desc.1", "The tag view cell filters the terminal it is placed in based on a tag expression"),
    CONFIG_SECTION_TAG_VIEW_CELL_DESC_2("screen.crazyae2addons.config.section.tag_view_cell.desc.2", "instead of selected individual resources."),
    CONFIG_SECTION_PATTERN_MULTIPLIER_DESC_1("screen.crazyae2addons.config.section.pattern_multiplier.desc.1", "The pattern multiplier allows the player to multiply patterns, multiply them up to a limit,"),
    CONFIG_SECTION_PATTERN_MULTIPLIER_DESC_2("screen.crazyae2addons.config.section.pattern_multiplier.desc.2", "or clear all patterns inside it."),
    CONFIG_SECTION_PATTERN_MULTIPLIER_DESC_3("screen.crazyae2addons.config.section.pattern_multiplier.desc.3", "It can also multiply all patterns in any container when shift-right-clicked on it."),
    CONFIG_SECTION_CRAZY_PATTERN_PROVIDER_DESC_1("screen.crazyae2addons.config.section.crazy_pattern_provider.desc.1", "The crazy pattern provider starts with 72 pattern slots"),
    CONFIG_SECTION_CRAZY_PATTERN_PROVIDER_DESC_2("screen.crazyae2addons.config.section.crazy_pattern_provider.desc.2", "and can be upgraded using crazy upgrades."),
    CONFIG_SECTION_CRAZY_PATTERN_PROVIDER_DESC_3("screen.crazyae2addons.config.section.crazy_pattern_provider.desc.3", "Each upgrade adds 1 row (9 slots) to the pattern inventory."),
    CONFIG_SECTION_EJECTOR_DESC_1("screen.crazyae2addons.config.section.ejector.desc.1", "The ejector allows the player to configure its 36-slot config inventory"),
    CONFIG_SECTION_EJECTOR_DESC_2("screen.crazyae2addons.config.section.ejector.desc.2", "with any amount of any resource."),
    CONFIG_SECTION_EJECTOR_DESC_3("screen.crazyae2addons.config.section.ejector.desc.3", "When provided with a redstone signal, it ejects those resources to the adjacent inventory."),
    CONFIG_SECTION_EJECTOR_DESC_4("screen.crazyae2addons.config.section.ejector.desc.4", "It can also craft missing resources if the system has the required patterns and ingredients."),
    CONFIG_SECTION_EJECTOR_DESC_5("screen.crazyae2addons.config.section.ejector.desc.5", "Crafting is performed atomically using one crafting job / CPU."),
    CONFIG_SECTION_PORTABLE_SPATIAL_STORAGE_DESC_1("screen.crazyae2addons.config.section.portable_spatial_storage.desc.1", "Portable spatial storage can cut structures from the world,"),
    CONFIG_SECTION_PORTABLE_SPATIAL_STORAGE_DESC_2("screen.crazyae2addons.config.section.portable_spatial_storage.desc.2", "rotate or flip them, and then paste them back,"),
    CONFIG_SECTION_PORTABLE_SPATIAL_STORAGE_DESC_3("screen.crazyae2addons.config.section.portable_spatial_storage.desc.3", "while preserving block NBT and other metadata."),
    CONFIG_SECTION_PORTABLE_SPATIAL_CLONER_DESC_1("screen.crazyae2addons.config.section.portable_spatial_cloner.desc.1", "Portable spatial cloner can copy structures from the world,"),
    CONFIG_SECTION_PORTABLE_SPATIAL_CLONER_DESC_2("screen.crazyae2addons.config.section.portable_spatial_cloner.desc.2", "rotate or flip them, and then paste them back,"),
    CONFIG_SECTION_PORTABLE_SPATIAL_CLONER_DESC_3("screen.crazyae2addons.config.section.portable_spatial_cloner.desc.3", "while preserving machine settings and supported modded metadata."),
    CONFIG_DESC_UNLIMITED_MINUS_ONE("screen.crazyae2addons.config.desc.unlimited_minus_one", "-1 means no limit."),
    CONFIG_DESC_DISPLAY_ENABLED("screen.crazyae2addons.config.desc.display.enabled", "Enable or disable the entire display feature."),
    CONFIG_DESC_DISPLAY_IMAGES_ENABLED("screen.crazyae2addons.config.desc.display.images_enabled", "Enable or disable uploading and rendering custom images on displays."),
    CONFIG_DESC_DISPLAY_STOCK_ENABLED("screen.crazyae2addons.config.desc.display.stock_enabled", "Enable or disable dynamic rendering of resource amounts from the connected network on displays."),
    CONFIG_DESC_DISPLAY_ICONS_ENABLED("screen.crazyae2addons.config.desc.display.icons_enabled", "Enable or disable rendering inline resource icons on displays."),
    CONFIG_DESC_DISPLAY_DELTA_ENABLED("screen.crazyae2addons.config.desc.display.delta_enabled", "Enable or disable dynamic rendering of resource amount changes over time on displays."),
    CONFIG_DESC_EMITTER_TERMINAL_ENABLED("screen.crazyae2addons.config.desc.emitter_terminal.enabled", "Enable or disable the emitter terminal feature."),
    CONFIG_DESC_WIRELESS_VARIANT_ENABLED("screen.crazyae2addons.config.desc.wireless_variant.enabled", "Enable or disable the wireless variant."),
    CONFIG_DESC_WIRELESS_NOTIFICATION_ENABLED("screen.crazyae2addons.config.desc.wireless_notification.enabled", "Enable or disable the wireless notification terminal feature."),
    CONFIG_DESC_WIRELESS_NOTIFICATION_CONFIG_SLOTS("screen.crazyae2addons.config.desc.wireless_notification.config_slots", "Configure how many slots the wireless notification terminal should have."),
    CONFIG_DESC_MULTI_LEVEL_EMITTER_ENABLED("screen.crazyae2addons.config.desc.multi_level_emitter.enabled", "Enable or disable the multi level emitter feature."),
    CONFIG_DESC_MULTI_LEVEL_EMITTER_CONFIG_SLOTS("screen.crazyae2addons.config.desc.multi_level_emitter.config_slots", "Configure how many slots the multi level emitter should have."),
    CONFIG_DESC_TAG_LEVEL_EMITTER_ENABLED("screen.crazyae2addons.config.desc.tag_level_emitter.enabled", "Enable or disable the tag level emitter feature."),
    CONFIG_DESC_REDSTONE_EMITTER_TERMINAL_ENABLED("screen.crazyae2addons.config.desc.redstone_emitter_terminal.enabled", "Enable or disable the redstone emitter / terminal feature."),
    CONFIG_DESC_WORMHOLE_ENABLED("screen.crazyae2addons.config.desc.wormhole.enabled", "Enable or disable the entire wormhole feature."),
    CONFIG_DESC_WORMHOLE_TELEPORTATION_1("screen.crazyae2addons.config.desc.wormhole.teleportation.1", "Enable or disable teleportation through wormholes."),
    CONFIG_DESC_WORMHOLE_TELEPORTATION_2("screen.crazyae2addons.config.desc.wormhole.teleportation.2", "This controls whether clicking on a wormhole with an ender pearl teleports the player to the other side."),
    CONFIG_DESC_WORMHOLE_NESTED_P2PS("screen.crazyae2addons.config.desc.wormhole.nested_p2ps", "Allow routing P2P tunnels through a wormhole tunnel."),
    CONFIG_DESC_WORMHOLE_ITEM_PROXY("screen.crazyae2addons.config.desc.wormhole.item_proxy", "Allow item proxying through wormholes."),
    CONFIG_DESC_WORMHOLE_FLUID_PROXY("screen.crazyae2addons.config.desc.wormhole.fluid_proxy", "Allow fluid proxying through wormholes."),
    CONFIG_DESC_WORMHOLE_FE_PROXY("screen.crazyae2addons.config.desc.wormhole.fe_proxy", "Allow FE proxying through wormholes."),
    CONFIG_DESC_WORMHOLE_EU_PROXY("screen.crazyae2addons.config.desc.wormhole.eu_proxy", "Allow GregTech EU proxying through wormholes."),
    CONFIG_DESC_WORMHOLE_OTHER_CAPABILITY_1("screen.crazyae2addons.config.desc.wormhole.other_capability.1", "Allow proxying of other capabilities through wormholes."),
    CONFIG_DESC_WORMHOLE_OTHER_CAPABILITY_2("screen.crazyae2addons.config.desc.wormhole.other_capability.2", "Example: Mekanism heat pipes."),
    CONFIG_DESC_WORMHOLE_MERGED_CAPABILITY_1("screen.crazyae2addons.config.desc.wormhole.merged_capability.1", "Allow merged capability proxying through wormholes."),
    CONFIG_DESC_WORMHOLE_MERGED_CAPABILITY_2("screen.crazyae2addons.config.desc.wormhole.merged_capability.2", "This allows the input side to see all matching output handlers at the same time."),
    CONFIG_DESC_WORMHOLE_REMOTE_INTERACTIONS_1("screen.crazyae2addons.config.desc.wormhole.remote_interactions.1", "Allow remote interactions through wormholes."),
    CONFIG_DESC_WORMHOLE_REMOTE_INTERACTIONS_2("screen.crazyae2addons.config.desc.wormhole.remote_interactions.2", "This controls whether clicking one side opens the GUI of the machine on the other side."),
    CONFIG_DESC_RR_ITEM_P2P("screen.crazyae2addons.config.desc.round_robin.item_p2p", "Enable or disable round robin item P2P."),
    CONFIG_DESC_RR_FLUID_P2P("screen.crazyae2addons.config.desc.round_robin.fluid_p2p", "Enable or disable round robin fluid P2P."),
    CONFIG_DESC_CPU_PRIORITIES("screen.crazyae2addons.config.desc.cpu_priorities.enabled", "Enable or disable CPU priorities."),
    CONFIG_DESC_TAG_VIEW_CELL("screen.crazyae2addons.config.desc.tag_view_cell.enabled", "Enable or disable tag view cells."),
    CONFIG_DESC_PATTERN_MULTIPLIER("screen.crazyae2addons.config.desc.pattern_multiplier.enabled", "Enable or disable the pattern multiplier feature."),
    CONFIG_DESC_CRAZY_PATTERN_PROVIDER_BLOCK("screen.crazyae2addons.config.desc.crazy_pattern_provider.block", "Enable or disable the crazy pattern provider block."),
    CONFIG_DESC_CRAZY_PATTERN_PROVIDER_PART("screen.crazyae2addons.config.desc.crazy_pattern_provider.part", "Enable or disable the crazy pattern provider part."),
    CONFIG_DESC_CRAZY_PROVIDER_MAX_UPGRADES("screen.crazyae2addons.config.desc.crazy_pattern_provider.max_upgrades", "Maximum number of upgrades allowed for the crazy pattern provider."),
    CONFIG_DESC_CRAZY_PROVIDER_MAX_UPGRADES_NOTE("screen.crazyae2addons.config.desc.crazy_pattern_provider.max_upgrades_note", "Each upgrade adds 1 row (9 slots)."),
    CONFIG_DESC_EJECTOR_ENABLED("screen.crazyae2addons.config.desc.ejector.enabled", "Enable or disable the ejector feature."),
    CONFIG_DESC_EJECTOR_CRAFT_MISSING("screen.crazyae2addons.config.desc.ejector.craft_missing", "Allow the ejector to craft missing items."),
    CONFIG_DESC_PSS_ENABLED("screen.crazyae2addons.config.desc.portable_spatial_storage.enabled", "Enable or disable portable spatial storage."),
    CONFIG_DESC_PSS_COST_1("screen.crazyae2addons.config.desc.portable_spatial_storage.cost.1", "Base AE cost of cutting or pasting one block."),
    CONFIG_DESC_PSS_COST_2("screen.crazyae2addons.config.desc.portable_spatial_storage.cost.2", "The final cost depends on this value and on the distance from the first selected corner."),
    CONFIG_DESC_PSS_BASE_POWER_1("screen.crazyae2addons.config.desc.portable_spatial_storage.base_power.1", "Base internal power capacity for portable spatial storage."),
    CONFIG_DESC_PSS_BASE_POWER_2("screen.crazyae2addons.config.desc.portable_spatial_storage.base_power.2", "Each energy upgrade adds this amount once more to the item's internal energy storage."),
    CONFIG_DESC_PSS_MAX_STRUCTURE_SIZE("screen.crazyae2addons.config.desc.portable_spatial_storage.max_structure_size", "Maximum allowed structure size for portable spatial storage."),
    CONFIG_DESC_PSC_ENABLED("screen.crazyae2addons.config.desc.portable_spatial_cloner.enabled", "Enable or disable portable spatial cloner."),
    CONFIG_DESC_PSC_COST_1("screen.crazyae2addons.config.desc.portable_spatial_cloner.cost.1", "Base AE cost of copying or pasting one block."),
    CONFIG_DESC_PSC_COST_2("screen.crazyae2addons.config.desc.portable_spatial_cloner.cost.2", "The final cost depends on this value and on the distance from the first selected corner."),
    CONFIG_DESC_PSC_BASE_POWER_1("screen.crazyae2addons.config.desc.portable_spatial_cloner.base_power.1", "Base internal power capacity for portable spatial cloner."),
    CONFIG_DESC_PSC_BASE_POWER_2("screen.crazyae2addons.config.desc.portable_spatial_cloner.base_power.2", "Each energy upgrade adds this amount once more to the item's internal energy storage."),
    CONFIG_DESC_PSC_MAX_STRUCTURE_SIZE("screen.crazyae2addons.config.desc.portable_spatial_cloner.max_structure_size", "Maximum allowed structure size for portable spatial cloner."),

    LANG("key", "val"),
    PROVIDER_MAX("gui.crazyae2addons.provider_max", "Maximum capacity reached!"),
    CRAZY_PROVIDER_CAPACITY_TOOLTIP("gui.crazyae2addons.crazy_provider_capacity_tooltip", "Capacity: "),
    MOD_NAME("gui.crazyae2addons.mod_name", "Crazy AE2 Addons"),
    PATTERNS("gui.crazyae2addons.patterns", "Patterns"),
    NOTHING("gui.crazyae2addons.nothing", "Nothing"),
    EJECTOR_LOAD_PATTERN("gui.crazyae2addons.ejector_load_pattern", "Load settings from pattern"),
    EJECTOR_MIDDLE_CLICK("gui.crazyae2addons.ejector_middle_click", "Middle mouse button to set amount"),
    BACK("gui.crazyae2addons.back", "Back"),
    ICON("gui.crazyae2addons.icon", "Icon"),
    STOCK("gui.crazyae2addons.stock", "Stock"),
    DELTA("gui.crazyae2addons.delta", "Delta"),
    INSERT("gui.crazyae2addons.insert", "Insert"),
    ANY("gui.crazyae2addons.any", "Any"),
    ITEM_ID_LABEL("gui.crazyae2addons.item_id_label", "Item ID:"),
    TYPE_LABEL("gui.crazyae2addons.type_label", "Type:"),
    DIVISOR_LABEL("gui.crazyae2addons.divisor_label", "Divisor:"),
    PER_LABEL("gui.crazyae2addons.per_label", "Per:"),
    WINDOW_LABEL("gui.crazyae2addons.window_label", "Window:"),
    KEY_TYPES_COLLAPSED("gui.crazyae2addons.key_types_collapsed", "Key types ▼"),
    KEY_TYPES_EXPANDED("gui.crazyae2addons.key_types_expanded", "Key types ▲"),
    TYPES_HEADER("gui.crazyae2addons.types_header", "Types"),
    DIV_RAW("gui.crazyae2addons.div_raw", "raw"),
    DIV_10("gui.crazyae2addons.div_10", "/10"),
    DIV_100("gui.crazyae2addons.div_100", "/100"),
    DIV_1K("gui.crazyae2addons.div_1k", "/1k"),
    DIV_10K("gui.crazyae2addons.div_10k", "/10k"),
    DIV_100K("gui.crazyae2addons.div_100k", "/100k"),
    DIV_1M("gui.crazyae2addons.div_1m", "/1M"),
    UNIT_TICKS("gui.crazyae2addons.unit_ticks", "t"),
    UNIT_SECONDS("gui.crazyae2addons.unit_seconds", "s"),
    UNIT_MINUTES("gui.crazyae2addons.unit_minutes", "m"),
    SAVE("gui.crazyae2addons.save", "Save"),
    INSERT_TOKEN("gui.crazyae2addons.insert_token", "Insert Token"),
    JOIN_DISPLAYS("gui.crazyae2addons.join_displays", "Join Displays"),
    ADD_MARGIN("gui.crazyae2addons.add_margin", "Add 3% Margin"),
    CENTER_TEXT("gui.crazyae2addons.center_text", "Center Text"),
    PICK_FILE("gui.crazyae2addons.pick_file", "Pick File"),
    REMOVE("gui.crazyae2addons.remove", "Remove"),
    IMAGES("gui.crazyae2addons.images", "Images"),
    BACKGROUND_COLOR("gui.crazyae2addons.background_color", "Background Color"),
    CHANGE_SELECTED_TEXT_COLOR("gui.crazyae2addons.change_selected_text_color", "Change Selected Text Color"),
    UNSAVED_CHANGES_TITLE("gui.crazyae2addons.unsaved_changes_title", "Are you sure?"),
    UNSAVED_CHANGES_TEXT("gui.crazyae2addons.unsaved_changes_text", "You have not saved the changes."),
    PICK_FILE_TOOLTIP("gui.crazyae2addons.pick_file_tooltip", "Pick and upload image"),
    REMOVE_IMAGE_TOOLTIP("gui.crazyae2addons.remove_image_tooltip", "Remove selected image"),
    IMAGE_LIST_TOOLTIP("gui.crazyae2addons.image_list_tooltip", "Uploaded images"),
    X_PERCENT("gui.crazyae2addons.x_percent", "X %"),
    Y_PERCENT("gui.crazyae2addons.y_percent", "Y %"),
    SCALE_PERCENT("gui.crazyae2addons.scale_percent", "Scale %"),
    X_PERCENT_TOOLTIP("gui.crazyae2addons.x_percent_tooltip", "Horizontal position in percent. 0 = left edge, 100 = right edge"),
    Y_PERCENT_TOOLTIP("gui.crazyae2addons.y_percent_tooltip", "Vertical position in percent. 0 = top edge, 100 = bottom edge"),
    SCALE_PERCENT_TOOLTIP("gui.crazyae2addons.scale_percent_tooltip", "Image scale in percent"),
    IMAGE_UPLOAD_OK("gui.crazyae2addons.image_upload_ok", "Image uploaded"),
    IMAGE_UPLOAD_CANCELLED("gui.crazyae2addons.image_upload_cancelled", "Image selection cancelled"),
    IMAGE_UPLOAD_CLIPBOARD_EMPTY("gui.crazyae2addons.image_upload_clipboard_empty", "Clipboard is empty"),
    IMAGE_UPLOAD_INVALID_PATH("gui.crazyae2addons.image_upload_invalid_path", "Clipboard does not contain a valid file path"),
    IMAGE_UPLOAD_INVALID_IMAGE("gui.crazyae2addons.image_upload_invalid_image", "Unsupported or corrupted image file"),
    IMAGE_UPLOAD_TOO_LARGE("gui.crazyae2addons.image_upload_too_large", "Image file is too large (%s bytes)"),
    IMAGE_UPLOAD_FAILED("gui.crazyae2addons.image_upload_failed", "Failed to upload image"),
    PREVIEW_DIMENSIONS("gui.crazyae2addons.preview_dimensions", "Preview %sx%s"),
    IMAGE_PREVIEW_BOUNDS("gui.crazyae2addons.image_preview_bounds", "%s%% @ %s,%s"),
    MISSING("gui.crazyae2addons.missing", "Missing"),
    CONFIG("gui.crazyae2addons.config", "Config"),
    INSERT_IMAGES("gui.crazyae2addons.display_images", "Insert Images"),
    NOTIFICATION_TERMINAL_UNIT_LINE("gui.crazyae2addons.notification_terminal.unit_line", "Unit: %s"),
    NOTIFICATION_TERMINAL_DISABLED("gui.crazyae2addons.notification_terminal.disabled", "Disabled"),
    NOTIFICATION_TERMINAL_INVALID_NUMBER("gui.crazyae2addons.notification_terminal.invalid_number", "Invalid number"),
    NOTIFICATION_TERMINAL_HUD_X_TOOLTIP("gui.crazyae2addons.notification_terminal.hud_x_tooltip", "Hud X in % (0-100)"),
    NOTIFICATION_TERMINAL_HUD_Y_TOOLTIP("gui.crazyae2addons.notification_terminal.hud_y_tooltip", "Hud Y in % (0-100)"),
    NOTIFICATION_TERMINAL_HIDE_ABOVE_TOOLTIP("gui.crazyae2addons.notification_terminal.hide_above_tooltip", "Do not render entries that are >= threshold"),
    NOTIFICATION_TERMINAL_HIDE_BELOW_TOOLTIP("gui.crazyae2addons.notification_terminal.hide_below_tooltip", "Do not render entries that are < threshold"),
    AND("gui.crazyae2addons.and", "AND"),
    OR("gui.crazyae2addons.or", "OR"),
    ITEMS("gui.crazyae2addons.items", "Items"),
    INVALID_NUMBER("gui.crazyae2addons.invalid_number", "Invalid number"),
    MULTI_EMITTER_LOGIC("gui.crazyae2addons.multi_emitter.logic", "Logic mode"),
    MULTI_EMITTER_CMP_ABOVE("gui.crazyae2addons.multi_emitter.cmp_above", "Emit when above or equal"),
    MULTI_EMITTER_CMP_BELOW("gui.crazyae2addons.multi_emitter.cmp_below", "Emit when below"),
    MULTI_EMITTER_EMIT_WHEN_CRAFTING("gui.crazyae2addons.multi_emitter.emit_when_crafting", "Emit when crafting"),
    MULTI_EMITTER_EMIT_WHEN_NOT_CRAFTING("gui.crazyae2addons.multi_emitter.emit_when_not_crafting", "Emit when not crafting"),
    MULTI_EMITTER_UNIT_LINE("gui.crazyae2addons.multi_emitter.unit_line", "Unit: %s"),
    EMITTER_TERMINAL_SEARCH("gui.crazyae2addons.emitter_terminal.search", "Search"),
    EXPRESSION_HINT("gui.crazyae2addons.expression_hint", "Expression"),
    THRESHOLD_TOOLTIP("gui.crazyae2addons.threshold_tooltip", "Threshold value"),
    APPLY("gui.crazyae2addons.apply", "Apply"),
    SEARCH("gui.crazyae2addons.search", "Search"),
    NAME("gui.crazyae2addons.name", "Name"),
    FLIP_HORIZONTAL("gui.crazyae2addons.flip_horizontal", "Flip horizontally in place"),
    FLIP_VERTICAL("gui.crazyae2addons.flip_vertical", "Flip vertically in place"),
    ROTATE_CLOCKWISE("gui.crazyae2addons.rotate_clockwise", "Rotate clockwise in place"),
    NO_BLOCK_IN_RANGE("gui.crazyae2addons.no_block_in_range", "No block in range."),
    PASTE_OR_CLEAR_FIRST("gui.crazyae2addons.paste_or_clear_first", "Paste or clear stored structure first."),
    CORNER_0_SELECTED("gui.crazyae2addons.corner_0_selected", "Shift Right click a block to select it."),
    CORNER_A_SELECTED("gui.crazyae2addons.corner_a_selected", "Right click to select another."),
    CORNER_B_SELECTED("gui.crazyae2addons.corner_b_selected", "Right click air to cut or shift click block to cancel."),
    SELECTION_RESTARTED("gui.crazyae2addons.selection_restarted", "Selection restarted."),
    FAILED_TO_SAVE_STRUCTURE("gui.crazyae2addons.failed_to_save_structure", "Failed to save structure."),
    STRUCTURE_CUT_AND_SAVED("gui.crazyae2addons.structure_cut_and_saved", "Right click to paste."),
    FAILED_TO_LOAD_STRUCTURE("gui.crazyae2addons.failed_to_load_structure", "Failed to load structure."),
    STORED_STRUCTURE_NOT_FOUND("gui.crazyae2addons.stored_structure_not_found", "Stored structure not found."),
    FAILED_TO_PASTE_STRUCTURE("gui.crazyae2addons.failed_to_paste_structure", "Failed to paste structure."),
    STRUCTURE_PASTED("gui.crazyae2addons.structure_pasted", "Structure pasted."),
    PASTE_COLLISION("gui.crazyae2addons.paste_collision", "Cannot paste structure: collision detected."),
    OFFSET_X_TOOLTIP("gui.crazyae2addons.offset_x_tooltip", "X offset"),
    OFFSET_Y_TOOLTIP("gui.crazyae2addons.offset_y_tooltip", "Y offset"),
    OFFSET_Z_TOOLTIP("gui.crazyae2addons.offset_z_tooltip", "Z offset"),
    OFFSET_LEFT_TOOLTIP("gui.crazyae2addons.offset_left_tooltip", "Move left (-X)"),
    OFFSET_RIGHT_TOOLTIP("gui.crazyae2addons.offset_right_tooltip", "Move right (+X)"),
    OFFSET_UP_TOOLTIP("gui.crazyae2addons.offset_up_tooltip", "Move up (+Y)"),
    OFFSET_DOWN_TOOLTIP("gui.crazyae2addons.offset_down_tooltip", "Move down (-Y)"),
    OFFSET_FRONT_TOOLTIP("gui.crazyae2addons.offset_front_tooltip", "Move forward (+Z)"),
    OFFSET_BACK_TOOLTIP("gui.crazyae2addons.offset_back_tooltip", "Move backward (-Z)"),
    CUT_COST_PREVIEW("gui.crazyae2addons.cut_cost_preview", "Cut: %s AE"),
    PASTE_COST_PREVIEW("gui.crazyae2addons.paste_cost_preview", "Paste: %s AE"),
    NOT_ENOUGH_POWER("gui.crazyae2addons.not_enough_power", "Not enough power"),
    NEED_AE("gui.crazyae2addons.need_ae", "Need: %s AE"),
    HAVE_AE("gui.crazyae2addons.have_ae", "Have: %s AE"),
    STRUCTURE_COPIED_AND_SAVED("gui.crazyae2addons.structure_copied_and_saved", "Structure copied and saved."),
    NO_MATERIALS("gui.crazyae2addons.no_materials", "No materials"),
    REQUIRED_COUNT("gui.crazyae2addons.required_count", "Required: %s"),
    FORGET_STRUCTURE("gui.crazyae2addons.forget_structure", "Forget stored structure."),
    FLIP_HORIZONTAL_AROUND_ORIGIN("gui.crazyae2addons.flip_horizontal_around_origin", "Flip horizontally around origin."),
    FLIP_VERTICAL_AROUND_ORIGIN("gui.crazyae2addons.flip_vertical_around_origin", "Flip vertically around origin."),
    ROTATE_CLOCKWISE_AROUND_ORIGIN("gui.crazyae2addons.rotate_clockwise_around_origin", "Rotate clockwise around origin."),
    AVAILABLE_COUNT("gui.crazyae2addons.available_count", "Available: %s"),
    STATUS_OK("gui.crazyae2addons.status_ok", "Status: OK"),
    STATUS_MISSING("gui.crazyae2addons.status_missing", "Status: Missing"),
    CRAFT_REQUEST_MISSING("gui.crazyae2addons.craft_request_missing", "Craft missing amount."),
    COPY_PASTE_NO_STRUCTURE("gui.crazyae2addons.copy_paste_no_structure", "No stored structure."),
    APPLY_MULTIPLIER("gui.crazyae2addons.apply_multiplier", "Apply multiplier"),
    CLEAR_ALL_PATTERNS("gui.crazyae2addons.clear_all_pattern", "Clear ALL patterns"),
    MULTIPLIER("gui.crazyae2addons.multiplier", "Multiplier"),
    PATTERN_MULTIPLIER_VALUE_TOOLTIP("gui.crazyae2addons.pattern_multiplier_value_tooltip", "Enter the multiplier value."),
    OUTPUT_LIMIT("gui.crazyae2addons.output_limit", "Output limit"),
    CANCEL_ALL_CRAFTING("gui.crazyae2addons.cancel_all_crafting", "Cancel all crafting"),
    PRIORITY("gui.crazyae2addons.priority", "Priority"),
    TAG_VIEW_CELL_INPUT("gui.crazyae2addons.tag_view_cell_input", "e.g. forge:ingots/*..."),
    FABRICATION_CATEGORY("emi.crazyae2addons.category_fabrication", "Recipe Fabricator"),
    RECIPE_FABRICATOR_PROGRESS("gui.crazyae2addons.recipe_fabricator_progress", "Progress: %s%%"),
    RECIPE_FABRICATOR_FLUID_IN("gui.crazyae2addons.recipe_fabricator_fluid_in", "Fluid In"),
    RECIPE_FABRICATOR_FLUID_OUT("gui.crazyae2addons.recipe_fabricator_fluid_out", "Fluid Out"),
    MB_AMOUNT("gui.crazyae2addons.mb_amount", "%s mB"),
    EMPTY("gui.crazyae2addons.empty", "Empty"),
    INPUT("gui.crazyae2addons.input", "Input"),
    OUTPUT("gui.crazyae2addons.output", "Output"),
    FEATURE_DISABLED("gui.crazyae2addons.feature_disabled", "DISABLED"),
    FEATURE_DISABLED_CONFIG("gui.crazyae2addons.feature_disabled_config", "in config"),
    DISPLAY_PREVIEW_SIZE("gui.crazyae2addons.display_preview_size", "Preview %1$s × %2$s"),
    NOTIFICATION_TERMINAL_HUD_SCALE_TOOLTIP("gui.crazyae2addons.notification_terminal.hud_scale_tooltip", "Hud scale in % (0-100)"),
    STRUCTURE_TOO_LARGE("gui.crazyae2addons.structure_too_large", "Structure too large"),
    STRUCTURE_SIZE("gui.crazyae2addons.structure_size", "Blocks: %s"),
    STRUCTURE_SIZE_LIMIT("gui.crazyae2addons.structure_size_limit", "Limit: %s"),
    ANALOG_OUTPUT_MODE("gui.crazyae2addons.analog_output.mode", "Analog Output Mode"),
    ANALOG_OUTPUT_LINEAR_DESC("gui.crazyae2addons.analog_output.linear.desc", "Linear signal based on stored amount."),
    ANALOG_OUTPUT_LOGARITHMIC_DESC("gui.crazyae2addons.analog_output.logarithmic.desc", "Logarithmic signal scaled for large storages."),
    STRUCTURE_GADGET_UNDO("gui.crazyae2addons.structure_gadget_undo", "Undo"),
    STRUCTURE_GADGET_NOTHING_TO_UNDO("gui.crazyae2addons.structure_gadget_nothing_to_undo", "Nothing to undo."),
    STRUCTURE_GADGET_UNDO_OTHER_DIMENSION("gui.crazyae2addons.structure_gadget_undo_other_dimension", "Undo is in another dimension."),
    STRUCTURE_GADGET_UNDO_INVALID_CLEARED("gui.crazyae2addons.structure_gadget_undo_invalid_cleared", "Invalid undo data cleared."),
    STRUCTURE_GADGET_CANNOT_UNDO_CUT("gui.crazyae2addons.structure_gadget_cannot_undo_cut", "Cannot undo cut."),
    STRUCTURE_GADGET_STORED_STRUCTURE_MISSING("gui.crazyae2addons.structure_gadget_stored_structure_missing", "Stored structure is missing."),
    STRUCTURE_GADGET_CUT_UNDONE("gui.crazyae2addons.structure_gadget_cut_undone", "Cut undone."),
    STRUCTURE_GADGET_PASTE_UNDONE("gui.crazyae2addons.structure_gadget_paste_undone", "Paste undone."),
    STRUCTURE_GADGET_STRUCTURE_CUT_BACK("gui.crazyae2addons.structure_gadget_structure_cut_back", "Structure cut back."),
    STRUCTURE_GADGET_ENERGY_REFUNDED("gui.crazyae2addons.structure_gadget_energy_refunded", "Energy refunded."),
    STRUCTURE_GADGET_SELECTION_CLEARED("gui.crazyae2addons.structure_gadget_selection_cleared", "Selection cleared."),
    STRUCTURE_GADGET_DIMENSION_CHANGED("gui.crazyae2addons.structure_gadget_dimension_changed", "You changed dimension."),
    STRUCTURE_GADGET_SELECTION_EMPTY_OR_SKIPPED("gui.crazyae2addons.structure_gadget_selection_empty_or_skipped", "Selected area is empty or contains only skipped blocks."),
    STRUCTURE_GADGET_NOTHING_CAPTURED("gui.crazyae2addons.structure_gadget_nothing_captured", "Nothing was captured."),
    STRUCTURE_GADGET_STORED_STRUCTURE_EMPTY("gui.crazyae2addons.structure_gadget_stored_structure_empty", "Stored structure is empty."),
    STRUCTURE_GADGET_INVALID_STRUCTURE_CLEARED("gui.crazyae2addons.structure_gadget_invalid_structure_cleared", "The invalid structure was cleared."),
    STRUCTURE_GADGET_UNDO_HINT("gui.crazyae2addons.structure_gadget_undo_hint", "Hold in offhand and right click to undo"),
    STRUCTURE_GADGET_COPY_PASTE_UNDONE("gui.crazyae2addons.structure_gadget_copy_paste_undone", "Copy paste undone."),
    STRUCTURE_GADGET_ITEMS_REFUNDED("gui.crazyae2addons.structure_gadget_items_refunded", "Items refunded."),
    STRUCTURE_GADGET_UNDO_NO_SPACE("gui.crazyae2addons.structure_gadget_undo_no_space", "Not enough space for refunded items."),
    STRUCTURE_GADGET_UNDO_WORLD_CHANGED("gui.crazyae2addons.structure_gadget_undo_world_changed", "Cannot undo: pasted blocks were changed."),
    STRUCTURE_GADGET_UNDO_NOTHING_PLACED("gui.crazyae2addons.structure_gadget_undo_nothing_placed", "Undo data contains no placed blocks."),
    STRUCTURE_GADGET_PLACED("gui.crazyae2addons.structure_gadget_placed", "Placed: %s"),
    STRUCTURE_GADGET_SKIPPED("gui.crazyae2addons.structure_gadget_skipped", "Skipped: %s"),
    STRUCTURE_GADGET_PLACED_SKIPPED("gui.crazyae2addons.structure_gadget_placed_skipped", "Placed: %s, skipped: %s"),
    STRUCTURE_GADGET_ITEMS_REFUNDED_TO_ME("gui.crazyae2addons.structure_gadget_items_refunded_to_me", "Items returned to ME storage."),
    STRUCTURE_GADGET_CLONER_EMPTY("gui.crazyae2addons.structure_gadget_cloner_empty", "<empty>"),
    STRUCTURE_GADGET_CLONER_SEARCH("gui.crazyae2addons.structure_gadget_cloner_search", "Search..."),
    STRUCTURE_GADGET_CLONER_SELECT("gui.crazyae2addons.structure_gadget_cloner_select", "Select"),
    STRUCTURE_GADGET_CLONER_RENAME("gui.crazyae2addons.structure_gadget_cloner_rename", "Rename"),
    STRUCTURE_GADGET_CLONER_NAME("gui.crazyae2addons.structure_gadget_cloner_name", "Name"),
    STRUCTURE_GADGET_CLONER_SELECTED("gui.crazyae2addons.structure_gadget_cloner_selected", "Structure selected."),
    STRUCTURE_GADGET_CLONER_RENAMED("gui.crazyae2addons.structure_gadget_cloner_renamed", "Structure renamed."),
    STRUCTURE_GADGET_CLONER_NOT_FOUND("gui.crazyae2addons.structure_gadget_cloner_not_found", "Structure not found."),
    STRUCTURE_GADGET_CLONER_LIBRARY_EMPTY("gui.crazyae2addons.structure_gadget_cloner_library_empty", "No saved structures."),
    STRUCTURE_GADGET_CLONER_SAVED("gui.crazyae2addons.structure_gadget_cloner_saved", "Clone saved."),
    STRUCTURE_GADGET_CLONER_DELETE("gui.crazyae2addons.structure_gadget_cloner_delete", "X"),
    STRUCTURE_GADGET_CLONER_EXPORT("gui.crazyae2addons.structure_gadget_cloner_export", "Export"),
    STRUCTURE_GADGET_CLONER_IMPORT("gui.crazyae2addons.structure_gadget_cloner_import", "Import"),
    STRUCTURE_GADGET_CLONER_EXPORT_TOOLTIP("gui.crazyae2addons.structure_gadget_cloner_export_tooltip", "Exports selected structure to a file you can send to someone."),
    STRUCTURE_GADGET_CLONER_IMPORT_TOOLTIP("gui.crazyae2addons.structure_gadget_cloner_import_tooltip", "Lets you choose a structure file exported with Export."),
    FLIP_EAST_WEST("gui.crazyae2addons.flip_east_west", "Flip East/West"),
    FLIP_EAST_WEST_AROUND_ORIGIN("gui.crazyae2addons.flip_east_west_around_origin", "Flip East/West around origin"),
    FLIP_NORTH_SOUTH("gui.crazyae2addons.flip_north_south", "Flip North/South"),
    FLIP_NORTH_SOUTH_AROUND_ORIGIN("gui.crazyae2addons.flip_north_south_around_origin", "Flip North/South around origin"),
    CONFIG_ENTRY_ENERGY_COST_MULTIPLIER("config.crazyae2addons.entry.energy_cost_multiplier", "Energy cost multiplier"),
    CONFIG_DESC_PSS_ENERGY_COST_MULTIPLIER_1("config.crazyae2addons.desc.pss_energy_cost_multiplier_1", "Multiplier applied to the distance-based AE cost for portable spatial storage."),
    CONFIG_DESC_PSS_ENERGY_COST_MULTIPLIER_2("config.crazyae2addons.desc.pss_energy_cost_multiplier_2", "Final cost is: base cost × block distance × multiplier."),
    CONFIG_DESC_PSC_ENERGY_COST_MULTIPLIER_1("config.crazyae2addons.desc.psc_energy_cost_multiplier_1", "Multiplier applied to the distance-based AE cost for portable spatial cloner."),
    CONFIG_DESC_PSC_ENERGY_COST_MULTIPLIER_2("config.crazyae2addons.desc.psc_energy_cost_multiplier_2", "Final cost is: base cost × block distance × multiplier."),
    CONFIG_DESC_ENERGY_COST_MULTIPLIER_ZERO("config.crazyae2addons.desc.energy_cost_multiplier_zero", "Set to 0 to disable energy cost for this gadget."),
    CONNECT_UP("gui.crazyae2addons.connect_up", "Connect Up"),
    CONNECT_DOWN("gui.crazyae2addons.connect_down", "Connect Down"),
    CONNECT_LEFT("gui.crazyae2addons.connect_left", "Connect Left"),
    CONNECT_RIGHT("gui.crazyae2addons.connect_right", "Connect Right"),
    DISPLAY_DATABASE_KEY("gui.crazyae2addons.display_database_key", "Key"),
    DISPLAY_DATABASE_VALUE("gui.crazyae2addons.display_database_value", "Value"),
    DISPLAY_DATABASE_ADD("gui.crazyae2addons.display_database_add", "Add"),
    DISPLAY_DATABASE_CLEAR("gui.crazyae2addons.display_database_clear", "Clear"),
    DISPLAY_DATABASE_ADD_TOOLTIP("gui.crazyae2addons.display_database_add_tooltip", "Add / update entry"),
    DISPLAY_DATABASE_CLEAR_TOOLTIP("gui.crazyae2addons.display_database_clear_tooltip", "Clear entries"),
    NO_ENTRIES("gui.crazyae2addons.no_entries", "No entries"),
    CONFIG_ENTRY_DISPLAY_DATABASE_ENABLED("config.crazyae2addons.entry.display_database_enabled", "Display Database Enabled"),
    CONFIG_DESC_DISPLAY_DATABASE_ENABLED("config.crazyae2addons.desc.display_database_enabled", "Enable or disable ME Display Database GUI, ComputerCraft peripheral and display database tokens.");


    private final String key;
    private final String value;

    LangDefs(String key, String value) {
        this.key = key;
        this.value = value;
    }

    @Override
    public String getTranslationKey() {
        return key;
    }

    @Override
    public String getEnglishText() {
        return value;
    }
}